/* eslint-disable */
// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/nonprofit/application.js
// or regenerate this file by running
// `./manage.py export nonprofit/applications`

  import Model from 'ember-data/model';


import attr from 'ember-data/attr';


import { belongsTo, hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    identity: attr('nullable'),
  
    version_start_date: attr('nullable'),
  
    version_end_date: attr('nullable'),
  
    version_birth_date: attr('nullable'),
  
    date: attr('nullable'),
  
    name: attr('string'),
  
    mission: attr('string'),
  
    products_and_services: attr('string'),
  
    ask: attr('string'),
  
    needs_hosting: attr('boolean'),
  
    needs_new_domain: attr('boolean'),
  
    url: attr('string'),
  
    __str__: attr('string'),
  
  
    representatives: hasMany('nonprofit/representative', {
      async: true,
      inverse: 'application',
    }),
  
    applicant: belongsTo('nonprofit/representative', {
      async: true,
      inverse: null,
    }),
  
});
