/* eslint-disable */
// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/nonprofit/organization.js
// or regenerate this file by running
// `./manage.py export nonprofit/organizations`

  import Model from 'ember-data/model';


import attr from 'ember-data/attr';


import { belongsTo } from 'ember-data/relationships';


export default Model.extend({
  
    date: attr('nullable'),
  
    invoice_type: attr('string'),
  
    state: attr('string'),
  
    __str__: attr('string'),
  
  
    related_party: belongsTo('crm/company', {
      async: true,
      inverse: 'organizations',
    }),
  
});
