/* eslint-disable */
// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/nonprofit/organization.js
// or regenerate this file by running
// `./manage.py export nonprofit/organizations`

  import Model from 'ember-data/model';


import attr from 'ember-data/attr';


import { hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    identity: attr('nullable'),
  
    version_start_date: attr('nullable'),
  
    version_end_date: attr('nullable'),
  
    version_birth_date: attr('nullable'),
  
    date: attr('nullable'),
  
    name: attr('string'),
  
    description: attr('string'),
  
    url: attr('string'),
  
    __str__: attr('string'),
  
  
    organizations: hasMany('nonprofit/representative', {
      async: true,
      inverse: 'organization',
    }),
  
});
